---
deployment:
  tasks:
    - composer install --no-dev --optimize-autoloader
    - npm install
    - npm run build
    - php artisan migrate
    - php artisan db:seed
    - php artisan storage:link
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan queue:restart
